-- Phase 7A: Closing team — documents + click-to-accept e-signature.
-- Run in the Supabase SQL editor. Safe to re-run (idempotent).

-- Proposals, service agreements, onboarding docs, offer letters. Generated by
-- the Document agent, approved by the CEO, then emailed to the lead with a
-- unique accept link. E-sign v1 = click-to-accept (records timestamp + IP).
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  lead_id uuid references public.leads(id) on delete cascade,
  type text not null check (type in ('proposal', 'agreement', 'onboarding', 'offer_letter')),
  title text not null,
  content_md text not null,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'sent', 'viewed', 'accepted', 'cancelled')),
  accept_token text not null unique,
  sent_at timestamptz,
  viewed_at timestamptz,
  accepted_at timestamptz,
  accepted_ip text,
  meta jsonb not null default '{}'::jsonb
);

alter table public.documents enable row level security;

drop policy if exists "Admin service role can manage documents" on public.documents;
create policy "Admin service role can manage documents"
on public.documents
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create index if not exists documents_lead_idx on public.documents (lead_id, created_at desc);
create index if not exists documents_token_idx on public.documents (accept_token);

-- Allow the document agent to be recorded in agent_runs.
alter table public.agent_runs drop constraint if exists agent_runs_agent_check;
alter table public.agent_runs add constraint agent_runs_agent_check
  check (agent in ('manager', 'qualify', 'research', 'email_draft', 'sequence_draft', 'scraper', 'negotiate', 'document'));
